export const plans = [
  {
    id: 1,
    day: "wednesday",
    functions: [
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
      {
        name: "Plan Name-2",
        duration: 25,
        question: 30,
        done: false,
        progress: true,
        error: false,
      },
      {
        name: "Plan Name-3",
        duration: 35,
        question: 40,
        done: false,
        progress: false,
        error: true,
      },
      {
        name: "Plan Name-4",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
    ],
  },
  {
    id: 2,
    day: "thursday",
    functions: [
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
      {
        name: "Plan Name-2",
        duration: 25,
        question: 30,
        done: false,
        progress: true,
        error: false,
      },
      {
        name: "Plan Name-3",
        duration: 35,
        question: 40,
        done: false,
        progress: false,
        error: true,
      },
      {
        name: "Plan Name-4",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
    ],
  },
  {
    id: 3,
    day: "friday",
    functions: [
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
      {
        name: "Plan Name-2",
        duration: 25,
        question: 30,
        done: false,
        progress: true,
        error: false,
      },
      {
        name: "Plan Name-3",
        duration: 35,
        question: 40,
        done: false,
        progress: false,
        error: true,
      },
      {
        name: "Plan Name-4",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
    ],
  },
  {
    id: 4,
    day: "saturday",
    functions: [
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
      {
        name: "Plan Name-2",
        duration: 25,
        question: 30,
        done: false,
        progress: true,
        error: false,
      },
      {
        name: "Plan Name-3",
        duration: 35,
        question: 40,
        done: false,
        progress: false,
        error: true,
      },
      {
        name: "Plan Name-4",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
    ],
  },
  {
    id: 5,
    day: "sunday",
    functions: [
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
      {
        name: "Plan Name-1",
        duration: 20,
        question: 25,
        done: false,
        progress: true,
        error: false,
      },
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
    ],
  },
  {
    id: 6,
    day: "monday",
    functions: [
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
      {
        name: "Plan Name-2",
        duration: 25,
        question: 30,
        done: false,
        progress: true,
        error: false,
      },
      {
        name: "Plan Name-3",
        duration: 35,
        question: 40,
        done: false,
        progress: false,
        error: true,
      },
      {
        name: "Plan Name-4",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
    ],
  },
  {
    id: 7,
    day: "tuesday",
    functions: [
      {
        name: "Plan Name-1",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
      {
        name: "Plan Name-2",
        duration: 25,
        question: 30,
        done: false,
        progress: true,
        error: false,
      },
      {
        name: "Plan Name-3",
        duration: 35,
        question: 40,
        done: false,
        progress: false,
        error: true,
      },
      {
        name: "Plan Name-4",
        duration: 15,
        question: 20,
        done: true,
        progress: false,
        error: false,
      },
    ],
  },
];
